INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Mohsen', 'Stroke' )
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Hassan','Lung cancer' )
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Ahmed',  'Leukemia')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Omar', 'Diabetes')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Bola', 'Cold')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Mostafa', 'Alzheimer')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Youssef', ' Anxiety')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Ali', 'Brain cancer')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Mahmoud', 'Asthma')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Karim' , ' Depression')
INSERT INTO Ent_Patient (Pname,Pdisease) VALUES ('Karam', 'Allergy')

INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Ahmed', 6000000)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Mohamed',6000001)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Omar',  6000002)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Karim', 6000003)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Bola',6000004)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Ali',6000005)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Mostafa',6000006)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Mahmoud',6000007)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Youssef' , 6000008)
INSERT INTO Ent_Doctor (DocName, WorksIn) VALUES ('Amr',6000009)

INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Mona', 6000001)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Mariam' ,6000000)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Amira' ,6000003)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Hagar', 6000004)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Esraa' , 6000005)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Asmaa' , 6000006)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Sara' ,  6000007)
INSERT INTO Ent_Nurse (NurName, WorksIn) VALUES ('Salma' , 6000008)

INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Ahmed',5000000)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Mohamed',5000001)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Youssef',5000002)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Karim',5000003)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Mahmoud',5000004)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Omar',5000005)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Hassan',5000006)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Ahmed',5000007)
INSERT INTO Ent_Wardboy (WarName, Maintains) VALUES ('Mohamed',5000008)



